(()=>{'use strict';const D=window.INTERVENTION_DATA,$=x=>document.getElementById(x),fmt=(v,n=3)=>v==null?'—':Number(v).toFixed(n),colors={BG0:'#172f40',baseline:'#777',early:'#177e89',middle:'#ad8038',late:'#bd5070',full:'#5868ac',background_early:'#78a059',background_full:'#496839',switch_bg_to_ref:'#bb784c',switch_ref_to_bg:'#744f9e'};let videoCases=[];
$('task').innerHTML=D.tasks.map(t=>`<option>${t}</option>`).join('');$('bg').innerHTML=Array.from({length:15},(_,i)=>`<option ${i===7?'selected':''}>BG${i+1}</option>`).join('');
$('status').textContent=`${D.complete?'전체 primary 분석 완료':'중간 결과 · 전체 실험 진행 중'} · ${D.completed}/${D.expected} primary rollouts · ${D.tracked} tracked videos`;
const key=(t,s,b,c)=>`${t}|${s}|${b}|${c}`,get=(t,s,b,c)=>D.cases[key(t,s,b,c)];
function chart(id,series,xlabel,ylabel,points=false){const all=series.flatMap(s=>s.rows).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));if(!all.length){$(id).innerHTML='<p class="small">측정 대기 / 유효한 값 없음</p>';return;}const W=560,H=300,L=77,R=22,T=22,B=63;let xmin=Math.min(...all.map(p=>p.x)),xmax=Math.max(...all.map(p=>p.x)),ymin=Math.min(0,...all.map(p=>p.y)),ymax=Math.max(0,...all.map(p=>p.y));let xp=(xmax-xmin||1)*.05,yp=(ymax-ymin||1)*.08;xmin-=xp;xmax+=xp;ymin-=yp;ymax+=yp;const X=x=>L+(x-xmin)/(xmax-xmin)*(W-L-R),Y=y=>H-B-(y-ymin)/(ymax-ymin)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${ylabel}">`;
for(let i=0;i<=4;i++){let x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg+=`<path d="M${L} ${Y(y)}H${W-R}" stroke="#dfe7ed"/><text x="${L-6}" y="${Y(y)+4}" font-size="10" text-anchor="end">${y.toPrecision(3)}</text><text x="${X(x)}" y="${H-B+18}" font-size="10" text-anchor="middle">${x.toPrecision(3)}</text>`;}
series.forEach((s,i)=>{let rs=s.rows.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),color=s.color||Object.values(colors)[i%9];if(!points)svg+=`<path d="${rs.map((p,j)=>`${j?'L':'M'}${X(p.x)} ${Y(p.y)}`).join(' ')}" stroke="${color}" fill="none" stroke-width="2"/>`;rs.forEach(p=>svg+=`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="${points?3:2}" fill="${color}" opacity=".8"><title>${s.name} ${p.label||''}: ${fmt(p.x,5)}, ${fmt(p.y,5)}</title></circle>`);});svg+=`<text x="${W/2}" y="${H-9}" font-size="11" text-anchor="middle">${xlabel}</text><text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" font-size="11" text-anchor="middle">${ylabel}</text></svg><div class="legend">${series.map((s,i)=>`<span style="color:${s.color||Object.values(colors)[i%9]}">● ${s.name}</span>`).join('')}</div>`;$(id).innerHTML=svg;}
function table(id,rows,columns){$(id).innerHTML='<table><tr>'+columns.map(([k,l])=>`<th>${l}</th>`).join('')+'</tr>'+rows.map(r=>'<tr>'+columns.map(([k])=>`<td>${typeof r[k]==='string'?r[k]:fmt(r[k])}</td>`).join('')+'</tr>').join('')+'</table>';}
function trajectory(id,cases,truth){let series=[];if(truth)series.push({name:'MuJoCo GT',color:'#999',rows:truth.map(p=>({x:p[0],y:-p[1]}))});for(const [label,c,col] of cases)if(c)series.push({name:label,color:col,rows:c.track.map(p=>({x:p[0],y:-p[1]}))});chart(id,series,'u (px)','−v (px; image vertical inverted)');}
function render(){const t=$('task').value,s=+$('seed').value,b=$('bg').value,step=+$('step').value,ref=get(t,s,'BG0','baseline'),base=get(t,s,b,'baseline'),early=get(t,s,b,'early'),late=get(t,s,b,'late'),full=get(t,s,b,'full');$('tau').textContent=`step ${step} · τ ${fmt(D.tau[step],4)}`;
const pairs=D.pairs,el=D.summary.find(r=>r.grouping==='pooled'&&r.metric==='Delta_EL');$('headline').textContent=el?`평균 Early−Late ${fmt(el.mean)} [95% CI ${fmt(el.ci_low)}, ${fmt(el.ci_high)}] · n=${el.n}${D.complete?'':' · 중간 결과'}`:'측정 진행 중';$('paired-result').textContent=$('headline').textContent;
$('input-qc').textContent=`BG0/BGb 기존 영상 재현·identity 검증 통과 · ${t}의 시간별 simulator mask`;const masksrc=`assets/${t}_mask.png`;if($('mask').getAttribute('src')!==masksrc)$('mask').src=masksrc;
const cs=['baseline','early','middle','late','full','background_early','background_full'].map(k=>get(t,s,b,k)).filter(Boolean);table('metrics',cs.map(c=>c.metric),[['condition','조건'],['D_BG_px','D_BG px'],['D_int_px','D_int px'],['Recovery','Recovery'],['ADE_GT','GT ADE px'],['FDE_GT','FDE px'],['confidence_min','Min conf.']]);
const vc=[['BG0',ref,'BG0'],[b,base,'baseline'],['Early',early,'early'],['Late',late,'late'],['Full',full,'full']];const signature=vc.map(([l,c])=>c?.video||l).join('|');if($('video-grid').dataset.signature!==signature){$('video-grid').dataset.signature=signature;$('video-grid').innerHTML=vc.map(([label,c])=>`<div class="card"><b>${label}</b>${c?`<div class="video"><video src="${c.video}" muted playsinline preload="metadata"></video><canvas width="256" height="256"></canvas></div>`:'<p>측정 대기</p>'}</div>`).join('');videoCases=vc.filter(x=>x[1]).map(x=>x[1]);}
trajectory('tracks',vc.map(([label,c,k])=>[label,c,colors[k]]),D.truth[t]);
const eff=get(t,s,b,$("correction-kind").value);if(eff){chart('flow-effect',[{name:'Before correction',rows:eff.flow.map((r,i)=>({x:i/35,y:r[0]}))},{name:'After correction',color:'#bd5070',rows:eff.flow.map((r,i)=>({x:i/35,y:r[1]}))}],'Denoising progress','Robot RMS to current-state BG0 flow');const r=eff.flow[step];$('flow-numbers').textContent=`${eff.metric.condition} · step ${step} · before ${fmt(r[0])} → after ${fmt(r[1])} · correction RMS ${fmt(r[2])} · 비개입 step의 반사실 flow는 미평가`;}else{$('flow-effect').innerHTML='<p>측정 대기</p>';$('flow-numbers').textContent='';}
for(const [id,j,label] of [['latent-raw',0,'Sampler x robot distance'],['latent-normalized',1,'Normalized z robot distance']])chart(id,cs.filter(c=>['baseline','early','late','full'].includes(c.metric.condition)).map(c=>({name:c.metric.condition,color:colors[c.metric.condition],rows:c.latent.slice(0,36).map((r,i)=>({x:i/35,y:r[j]}))})),'Denoising progress',label);
$('latent-end').textContent=cs.filter(c=>['baseline','early','late','full'].includes(c.metric.condition)).map(c=>`${c.metric.condition} final clean: ${fmt(c.latent[36]?.[0])}`).join(' · ');
table('summary',D.summary.filter(r=>r.grouping==='pooled'&&r.metric==='Recovery'),[['condition','조건'],['mean','평균'],['median','중앙값'],['ci_low','95% CI low'],['ci_high','high'],['n','n']]);
const group=$('group').value==='task'?t:$('group').value;const corr=D.correlations.filter(r=>r.grouping===group);table('correlations',corr,[['x','원래 flow'],['y','회복'],['rho','Spearman ρ'],['pearson','Pearson r'],['rho_ci_low','ρ CI low'],['rho_ci_high','high'],['n','n']]);
for(const stage of ['early','late']){let pts=pairs.filter(r=>r[`Recovery_${stage}`]!=null&&($('group').value!=='task'||r.task===t)).map(r=>({...r}));if(group==='task_demeaned')for(const task of D.tasks){const rs=pts.filter(r=>r.task===task);for(const k of [`D_flow_${stage}`,`Recovery_${stage}`]){const avg=rs.reduce((s,r)=>s+r[k],0)/rs.length;rs.forEach(r=>r[k]-=avg);}}chart('mechanism-'+stage,D.tasks.map(task=>({name:task,rows:pts.filter(r=>r.task===task).map(r=>({x:r[`D_flow_${stage}`],y:r[`Recovery_${stage}`],label:`seed${r.seed} ${r.background}`}))})),`Original ${stage} normalized drift${group==='task_demeaned'?' (centered)':''}`,`${stage} Recovery${group==='task_demeaned'?' (centered)':''}`,true);}
const switches=['switch_bg_to_ref','switch_ref_to_bg'].map(k=>get(t,s,b,k)).filter(Boolean),alphas=[.25,.5,.75].map(a=>get(t,s,b,`alpha_${a.toFixed(2)}`)).filter(Boolean);$('secondary-status').textContent=switches.length?`${switches.length}/2 switch conditions · ${alphas.length}/3 partial corrections`:'Primary 검증 후 실행 예정 / 측정 대기';trajectory('switch-tracks',[['BG0',ref,colors.BG0],[b,base,colors.baseline],...switches.map(c=>[c.metric.condition,c,colors[c.metric.condition]])],D.truth[t]);chart('alpha-curve',[{name:'Early α response',color:colors.early,rows:[...(base?[{x:0,y:base.metric.Recovery}]:[]),...alphas.map(c=>({x:+c.metric.condition.split('_')[1],y:c.metric.Recovery})),...(early?[{x:1,y:early.metric.Recovery}]:[])]}],'α','Recovery');table('secondary-table',[...switches,...alphas].map(c=>c.metric),[['condition','조건'],['D_BG_px','D_BG px'],['D_int_px','D_int px'],['Recovery','Recovery'],['ADE_GT','GT ADE px']]);}
function draw(){const videos=[...document.querySelectorAll('#video-grid video')];videos.forEach((v,i)=>{const c=videoCases[i],canvas=v.nextElementSibling,ctx=canvas.getContext('2d'),t=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);if(!c)return;ctx.strokeStyle='#00ffff';ctx.lineWidth=1.5;ctx.beginPath();for(let j=0;j<=t;j++){if(!c.valid[j])continue;const p=c.track[j];if(j===0||!c.valid[j-1])ctx.moveTo(...p);else ctx.lineTo(...p);}ctx.stroke();if(c.valid[t]){ctx.fillStyle='#00ffff';const p=c.track[t];ctx.beginPath();ctx.arc(p[0],p[1],3,0,2*Math.PI);ctx.fill();}});requestAnimationFrame(draw);}
$('play').onclick=()=>{const vs=[...document.querySelectorAll('#video-grid video')],playing=vs.some(v=>!v.paused);vs.forEach(v=>{if(playing)v.pause();else{v.currentTime=vs[0].currentTime;v.play().catch(()=>{});}});};$('reset').onclick=()=>document.querySelectorAll('#video-grid video').forEach(v=>{v.pause();v.currentTime=0;});
['task','seed','bg','group','correction-kind'].forEach(id=>$(id).addEventListener('change',render));$('step').addEventListener('input',render);render();draw();})();
