(()=>{'use strict';const D=window.CUMULATIVE_DATA,$=id=>document.getElementById(id),fmt=(x,n=2)=>x==null||!Number.isFinite(+x)?'—':(+x).toFixed(n),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),labels={baseline:'BGb baseline',spatial_E:'Full-spatial E',spatial_EM:'Full-spatial E+M',spatial_ML:'Full-spatial M+L',spatial_all:'Full-spatial All-steps'},colors={BG0:'#173746',baseline:'#777777',spatial_E:'#d18b28',spatial_EM:'#07857e',spatial_ML:'#b35b86',spatial_all:'#536bb2',GT:'#202a32'},KS=Object.keys(labels).slice(1);let sample=null,version=0,videos=[],trackFocus='Full-spatial E+M';
function table(id,rows,cols){$(id).innerHTML='<table><thead><tr>'+cols.map(c=>'<th>'+escape(c[1])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+escape(typeof c[0]==='function'?c[0](r):(r[c[0]]??'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
const ci=r=>r?`${fmt(r.mean)} [${fmt(r.ci_low)}, ${fmt(r.ci_high)}]`:'—';
function stat(k,m,g='pooled'){return D.summary.find(r=>r.cohort==='paired_windows'&&r.grouping===g&&r.condition===k&&r.metric===m);}
$('status').textContent=`${D.n_rollouts.toLocaleString()} new rollouts · ${D.n_samples} task/background/seed pairs · ${D.n_paired} jointly valid pairs · ${D.date}`;
$ ('scale-note').textContent=D.text.scale;
for(const id of ['main','matched','spatial','task','gt','region'])$(id+'-result').textContent=D.text[id];
table('summary',KS.map(k=>({k,...stat(k,'Recovery_pct')})),[[r=>labels[r.k],'Full-spatial window'],['n','Recovery n'],[r=>ci(r),'Mean recovery % [95% CI]'],[r=>fmt(r.median),'Median %'],[r=>fmt(stat(r.k,'D_BG_px').mean,3),'D_BG px'],[r=>fmt(stat(r.k,'ADE_BG0_px').mean,3),'ADE to BG0 px'],[r=>fmt(stat(r.k,'FDE_BG0_px').mean,3),'FDE to BG0 px'],[r=>ci(stat(r.k,'DeltaD_px')),'ΔD px [95% CI]']]);
table('contrasts',D.paired_summary.filter(r=>r.grouping==='pooled'&&r.metric==='Recovery_difference_pp'),[[r=>r.contrast.replaceAll('spatial_','').replaceAll('EM','E+M').replaceAll('ML','M+L').replaceAll('all','All-steps'),'Paired contrast'],['n','n'],[ci,'Difference %p [95% CI]'],[r=>r.ci_low>0?'Positive':r.ci_high<0?'Negative':'Inconclusive','CI direction']]);
table('spatial-table',D.spatial_summary.filter(r=>r.grouping==='pooled'&&r.metric==='Recovery_difference_pp'),[[r=>labels[r.window],'Matched window'],['n','n'],[ci,'Full-spatial − Robot-only %p [95% CI]']]);
table('historical',D.historical,[['label','Previous robot-only window'],['n','n'],[ci,'Recovery % [95% CI]']]);
table('task-table',D.tasks.map(t=>({task:t})),[['task','Task'],[r=>fmt(stat('spatial_EM','D_BG_px',r.task).mean,3),'D_BG px'],...KS.map(k=>[r=>fmt(stat(k,'Recovery_pct',r.task).mean),labels[k]+' %']),[r=>fmt(stat('spatial_EM','ADE_BG0_px',r.task).mean,3),'E+M ADE_BG0 px'],[r=>fmt(stat('spatial_EM','GT_improvement_px',r.task).mean,3),'E+M GT improvement px']]);
table('distribution-table',D.summary.filter(r=>r.cohort==='paired_windows'&&r.metric==='Recovery_pct'&&(/^(BG|seed)/).test(r.grouping)),[['grouping','Group'],[r=>labels[r.condition],'Window'],['n','n'],[ci,'Recovery % [95% CI]'],[r=>fmt(r.median),'Median %']]);
table('validation-table',D.validation,[['check','Check'],['result','Result']]);
table('sensitivity',D.sensitivity.filter(r=>r.metric==='Recovery_pct'),[['minimum_D_BG_px','Minimum baseline drift px'],[r=>labels[r.condition],'Window'],['n','n'],[ci,'Recovery % [95% CI]']]);
$('downloads-list').innerHTML=D.downloads.map(x=>`<a href="${escape(x.path)}">${escape(x.label)}</a>`).join('');
$('task').innerHTML=D.tasks.map(t=>`<option>${escape(t)}</option>`).join('');$('bg').innerHTML=Array.from({length:15},(_,i)=>`<option ${i===7?'selected':''}>BG${i+1}</option>`).join('');
function chart(id,series,opt={}){let xs=[],ys=[];series.forEach(s=>s.points.forEach(p=>{if(p[0]!=null&&p[1]!=null&&Number.isFinite(p[0])&&Number.isFinite(p[1])){xs.push(p[0]);ys.push(p[1]);}}));if(!xs.length){$(id).textContent='No valid data';return;}let W=600,H=360,L=66,R=24,T=35,B=66,x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys);if(opt.zero)y0=Math.min(0,y0);if(x1===x0)x1=x0+1;if(y1===y0)y1=y0+1;const yp=(y1-y0)*.08;y0-=yp;y1+=yp;if(opt.reverse){const scale=Math.min((W-L-R)/(x1-x0),(H-T-B)/(y1-y0)),cx=(x0+x1)/2,cy=(y0+y1)/2;const dx=(W-L-R)/scale/2,dy=(H-T-B)/scale/2;x0=cx-dx;x1=cx+dx;y0=cy-dy;y1=cy+dy;}let X=x=>L+(x-x0)/(x1-x0)*(W-L-R),Y=y=>T+(opt.reverse?(y-y0)/(y1-y0):1-(y-y0)/(y1-y0))*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${escape(opt.title||'Plot')}"><rect width="${W}" height="${H}" fill="white"/><text x="${L}" y="18" font-size="13" font-weight="600">${escape(opt.title||'')}</text>`;
if(opt.bands)for(const a of opt.bands)svg+=`<rect x="${X(a[0])}" y="${T}" width="${X(a[1])-X(a[0])}" height="${H-T-B}" fill="#d3eee8" opacity="0.5"/>`;
for(let i=0;i<=4;i++){let x=x0+(x1-x0)*i/4,y=y0+(y1-y0)*i/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${Y(y)}" y2="${Y(y)}" stroke="#e3e9eb"/><text x="${L-7}" y="${Y(y)+4}" text-anchor="end" font-size="10">${fmt(y,Math.abs(y1-y0)<.1?4:2)}</text><text x="${X(x)}" y="${H-B+18}" text-anchor="middle" font-size="10">${fmt(x,opt.reverse?0:2)}</text>`;}
const drawSeries=opt.focusName?[...series].sort((a,b)=>Number(a.name===opt.focusName)-Number(b.name===opt.focusName)):series;for(const s of drawSeries){const selected=s.name===opt.focusName;svg+=`<g data-series="${escape(s.name)}" opacity="${opt.focusName&&!selected?0.22:1}">`;let path='',last=false;for(const p of s.points){if(p[0]==null||p[1]==null){last=false;continue;}path+=(last?'L':'M')+X(p[0])+','+Y(p[1]);last=true;}svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="${selected?3.5:2}" ${s.dash?'stroke-dasharray="5 4"':''}/>`;for(const p of s.points)if(p[0]!=null&&p[1]!=null)svg+=`<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="${selected?4:2.5}" fill="${selected?'white':s.color}" stroke="${s.color}" stroke-width="${selected?2:0}"><title>${escape(s.name)} · ${escape(p[2]||'')} · ${fmt(p[1],5)}</title></circle>`;svg+='</g>';}
svg+=`<text x="${(W+L-R)/2}" y="${H-24}" text-anchor="middle" font-size="11">${escape(opt.x||'Denoising progress · high → low noise')}</text><text x="16" y="${H/2}" text-anchor="middle" transform="rotate(-90 16 ${H/2})" font-size="11">${escape(opt.y||'')}</text></svg><div class="small">${series.map(s=>opt.onFocus?`<button type="button" class="track-key" data-focus="${escape(s.name)}" aria-pressed="${s.name===opt.focusName}" style="color:${s.color}">${s.dash?'┄':'━'} ${escape(s.name)}</button>`:`<span style="color:${s.color}">${s.dash?'┄':'━'} ${escape(s.name)}</span>`).join(' · ')}</div>`;$(id).innerHTML=svg;if(opt.onFocus)$(id).querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>opt.onFocus(b.dataset.focus));}
function flow(){if(!sample)return;const k=$('window').value,metric=$('flow-metric').value,rows=sample.conditions[k].steps,bands=[];if(D.windows[k].includes(0))bands.push([0,(Math.max(...D.windows[k])+0.5)/35]);else bands.push([(Math.min(...D.windows[k])-.5)/35,1]);bands.forEach(x=>x[1]=Math.min(1,x[1]));chart('flow-chart',[['full','Entire tensor','#5063a4'],['robot','Robot mask','#d18b28'],['future_nonrobot','Future outside mask','#07857e']].map(([r,name,color])=>({name,color,points:rows.map(z=>[z.progress,z[metric+'_'+r],`step${z.step} τ=${fmt(z.tau,5)} σ=${fmt(z.sigma,5)}`])})),{title:'Same-current-state flow difference',y:metric==='RMS'?'RMS':'1 − cosine',zero:true,bands});chart('latent-chart',KS.map(k=>({name:labels[k],color:colors[k],points:sample.conditions[k].steps.map(z=>[z.progress,z.future_latent_BG0_RMS,`step${z.step} τ=${fmt(z.tau,5)}`])})),{title:'Future latent distance to BG0 path',y:'RMS',zero:true});}
function renderTracks(){if(!sample)return;const data=sample,entries=[['BG0',data.BG0],['baseline',data.BGb],...KS.map(k=>[k,data.conditions[k]])];chart('tracks',[...entries.map(([k,z])=>({name:k==='BG0'?'BG0':labels[k],color:colors[k],points:z.trajectory.map((p,i)=>z.valid[i]?[...p,`frame${i}`]:[null,null])})),{name:'MuJoCo GT',color:colors.GT,dash:true,points:data.GT.map((p,i)=>[...p,`frame${i}`])}],{title:`${$('task').value} / seed${$('seed').value} / ${$('bg').value}`,x:'u (px)',y:'v (px, downward)',reverse:true,focusName:trackFocus,onFocus:name=>{trackFocus=name;renderTracks();}});}
function drawTraces(){if(videos.length&&videos.every(z=>!z.v.paused)){const leader=videos[0].v.currentTime;for(const z of videos.slice(1))if(Math.abs(z.v.currentTime-leader)>.08)z.v.currentTime=leader;}for(const entry of videos){const {v,c,trajectory,valid,color}=entry;const ctx=c.getContext('2d'),f=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let prev=false;for(let i=0;i<=f;i++){if(!valid[i]){prev=false;continue;}const [x,y]=trajectory[i];if(prev)ctx.lineTo(x,y);else ctx.moveTo(x,y);prev=true;}ctx.stroke();if(valid[f]){const [x,y]=trajectory[f];ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();}}requestAnimationFrame(drawTraces);}
async function update(){const token=++version;videos.forEach(z=>z.v.pause());const task=$('task').value,seed=$('seed').value,bg=$('bg').value;$('sample-status').textContent='Loading sample…';const res=await fetch(`cumulative_cases/${task}/seed${seed}/${bg}.json`);if(!res.ok)throw Error('Sample load failed '+res.status);const data=await res.json();if(token!==version)return;sample=data;videos=[];const entries=[['BG0',data.BG0],['baseline',data.BGb],...KS.map(k=>[k,data.conditions[k]])];$('video-grid').innerHTML=entries.map(([k,z])=>`<div><div class="vlabel">${escape(k==='BG0'?'BG0 reference':labels[k])}</div><div class="vbox"><video src="${escape(z.video)}" preload="metadata" muted playsinline loop></video><canvas width="256" height="256"></canvas></div></div>`).join('');$('video-grid').querySelectorAll('.vbox').forEach((box,i)=>{const [k,z]=entries[i];videos.push({v:box.querySelector('video'),c:box.querySelector('canvas'),trajectory:z.trajectory,valid:z.valid,color:colors[k]});});
const stats=[data.baseline_metric,...KS.map(k=>data.conditions[k].metric)];table('sample-metrics',stats,[[r=>labels[r.condition],'Condition'],[r=>fmt(r.Recovery_pct),'Recovery %'],[r=>fmt(r.D_BG_px,3),'D_BG px'],[r=>fmt(r.ADE_BG0_px,3),'ADE_BG0 px'],[r=>fmt(r.FDE_BG0_px,3),'FDE_BG0 px'],[r=>fmt(r.DeltaD_px,3),'ΔD px'],[r=>fmt(r.ADE_GT_px,3),'ADE_GT px'],[r=>fmt(r.FDE_GT_px,3),'FDE_GT px']]);
renderTracks();$('sample-status').textContent=`${task} / seed${seed} / ${bg} · ${stats.some(r=>r.paired_tracker_failed)?'Tracking QC exclusion present: excluded metrics shown as —':'Tracking QC passed'} · 측정: 20 future frames / 재생: 21 frames at 10 fps`;flow();}
for(const id of ['task','seed','bg'])$(id).addEventListener('change',()=>update().catch(e=>{$('sample-status').textContent=e.message;console.error(e);}));for(const id of ['window','flow-metric'])$(id).addEventListener('change',flow);
$('play').onclick=async()=>{if(!videos.length)return;if(videos.some(z=>!z.v.paused)){videos.forEach(z=>z.v.pause());return;}const t=videos[0].v.currentTime;videos.forEach(z=>{z.v.currentTime=t;});await Promise.all(videos.map(z=>z.v.play()));};$('reset').onclick=()=>videos.forEach(z=>{z.v.pause();z.v.currentTime=0;});drawTraces();update().catch(e=>{console.error(e);$('sample-status').textContent=e.message;});if(['#middle-switch','#stage-flow-only','#late-switch'].includes(location.hash))document.getElementById('cumulative').scrollIntoView();
})();
