(()=>{'use strict';const F=window.EARLY_MIDDLE_DATA,D=window.INTERVENTION_DATA,H=window.INTERVENTION_RENDER_HELPERS,$=id=>document.getElementById(id),fmt=(v,n=3)=>v==null?'—':Number(v).toFixed(n),colors={BG0:'#172f40',baseline:'#777',early:'#177e89',middle:'#ad8038',early_middle:'#0b5263',late:'#bd5070',full:'#5868ac'};let videoCases=[];
Object.assign(D.cases,F.cases);
$('status').textContent+=` · Early+Middle 추가 ${F.metrics.length}/270 · 합계 ${D.tracked+F.metrics.length} videos · 추가 추적 QC 제외 ${F.tracking_failures.length}건`;
const st=F.summary.find(r=>r.group==='pooled'&&r.comparison==='early'&&r.metric==='Delta_recovery'),em=F.summary.find(r=>r.group==='pooled'&&r.comparison==='early_middle'&&r.metric==='Recovery');
$('em-headline').textContent=`Early+Middle 평균 회복 ${fmt(em.mean*100,2)}% · Early 대비 paired 차이 ${fmt(st.mean*100,2)}%p [95% CI ${fmt(st.ci_low*100,2)}, ${fmt(st.ci_high*100,2)}]%p · n=${st.n} · ${st.ci_low>0?'추가 회복 지지':st.ci_high<0?'회복 감소':'추가 이득 불확실'}`;
const conditionSummary=['early','middle','early_middle','late','full'].map(kind=>{const find=metric=>kind==='early_middle'?F.summary.find(r=>r.group==='pooled'&&r.comparison===kind&&r.metric===metric):D.summary.find(r=>r.grouping==='pooled'&&r.condition===kind&&r.metric===metric),rec=find('Recovery');return {condition:kind,n:rec.n,D_BG:find('D_BG_px').mean,D_int:find('D_int_px').mean,Recovery:rec.mean*100,lo:rec.ci_low*100,hi:rec.ci_high*100,ADE:find('ADE_GT').mean};});
H.table('em-condition-summary',conditionSummary,[['condition','조건'],['n','n'],['D_BG','D_BG px'],['D_int','D_int px'],['Recovery','회복 %'],['lo','95% CI low'],['hi','high'],['ADE','GT ADE px']]);
H.table('em-contrast-summary',F.summary.filter(r=>r.group==='pooled'&&r.metric==='Delta_recovery').map(r=>({...r,mean:r.mean*100,ci_low:r.ci_low*100,ci_high:r.ci_high*100,absolute:F.summary.find(a=>a.group==='pooled'&&a.comparison===r.comparison&&a.metric==='absolute_improvement_px').mean})),[['comparison','Early+Middle vs'],['n','paired n'],['mean','Δ 회복 %p'],['ci_low','95% CI low'],['ci_high','high'],['absolute','D_other − D_EM px']]);
H.table('em-task-summary',D.tasks.map(task=>{const a=F.summary.find(r=>r.group===task&&r.comparison==='early_middle'&&r.metric==='Recovery'),b=F.summary.find(r=>r.group===task&&r.comparison==='early'&&r.metric==='Delta_recovery');return {task,n:b.n,mean:a.mean*100,delta:b.mean*100};}),[['task','Task'],['n','paired n'],['mean','Early+Middle 회복 %'],['delta','Early 대비 Δ %p']]);
function render(){const t=$('task').value,s=+$('seed').value,b=$('bg').value,get=(bg,k)=>D.cases[`${t}|${s}|${bg}|${k}`],ref=get('BG0','baseline');
 const cs=['baseline','early','middle','early_middle','late','full'].map(k=>get(b,k));
 H.table('em-metrics',cs.map(c=>({...c.metric,QC:c.metric.tracker_failed||c.metric.paired_tracker_failed?'Excluded':'Valid'})),[['condition','조건'],['D_BG_px','D_BG px'],['D_int_px','D_int px'],['Recovery','Recovery'],['ADE_GT','GT ADE px'],['FDE_GT','FDE px'],['confidence_min','Min conf.'],['valid_future_fraction','Valid fraction'],['QC','Tracking QC']]);
 const vc=[['BG0',ref],...cs.filter(c=>c.metric.condition!=='late').map(c=>[c.metric.condition,c])];
 H.trajectory('em-tracks',vc.map(([name,c])=>[name,c,colors[name]]),D.truth[t]);
 H.chart('em-latent',cs.map(c=>({name:c.metric.condition,color:colors[c.metric.condition],rows:c.latent.slice(0,36).map((r,i)=>({x:i/35,y:r[1]}))})),'Denoising progress','Normalized robot latent distance to BG0');
 const signature=vc.map(([name,c])=>c.video).join('|');if($('em-videos').dataset.signature!==signature){$('em-videos').dataset.signature=signature;$('em-videos').innerHTML=vc.map(([name,c])=>`<div class="card"><b>${name==='early_middle'?'Early + Middle':name}</b>${c.metric.tracker_failed?'<span class="small"> · QC excluded</span>':''}<div class="video"><video src="${c.video}" muted playsinline preload="metadata"></video><canvas width="256" height="256"></canvas></div></div>`).join('');videoCases=vc.map(([name,c])=>c);}
}
function draw(){document.querySelectorAll('#em-videos video').forEach((v,i)=>{const c=videoCases[i],ctx=v.nextElementSibling.getContext('2d'),last=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);if(!c)return;ctx.strokeStyle='#00ffff';ctx.lineWidth=1.5;ctx.beginPath();for(let j=0;j<=last;j++){if(!c.valid[j])continue;if(j===0||!c.valid[j-1])ctx.moveTo(...c.track[j]);else ctx.lineTo(...c.track[j]);}ctx.stroke();if(c.valid[last]){ctx.fillStyle='#00ffff';ctx.beginPath();ctx.arc(...c.track[last],3,0,Math.PI*2);ctx.fill();}});requestAnimationFrame(draw);}
$('em-play').onclick=()=>{const vs=[...document.querySelectorAll('#em-videos video')],playing=vs.some(v=>!v.paused),time=vs[0].currentTime;vs.forEach(v=>{if(playing)v.pause();else{v.currentTime=time;v.play().catch(()=>{});}});};$('em-reset').onclick=()=>document.querySelectorAll('#em-videos video').forEach(v=>{v.pause();v.currentTime=0;});
['task','seed','bg'].forEach(id=>$(id).addEventListener('change',render));render();draw();})();
