(()=>{'use strict';const D=window.FLOW_ONLY_DATA,old=window.INTERVENTION_DATA,$=id=>document.getElementById(id),H=window.INTERVENTION_RENDER_HELPERS,fmt=(v,n=3)=>v==null?'—':Number(v).toFixed(n),stages=['early','middle','late','full'],colors={BG0:'#172f40',baseline:'#777',early:'#177e89',middle:'#ad8038',late:'#bd5070',full:'#5868ac'};let videos=[];
const get=(t,s,b,k)=>old.cases[`${t}|${s}|${b}|${k}`];const stat=(k,m,g='pooled',cohort='paired_stages')=>D.summary.find(r=>r.condition===k&&r.metric===m&&r.grouping===g&&r.cohort===cohort),ci=r=>`${fmt(r?.mean)} [${fmt(r?.ci_low)}, ${fmt(r?.ci_high)}]`;
const pr=D.paired_summary.filter(r=>r.grouping==='pooled'&&r.metric==='Recovery_difference_pp');
$('fo-headline').textContent=stages.map(k=>`${k}: ${fmt(stat(k,'Recovery_pct').mean,2)}%`).join(' · ')+' · paired n='+stat('early','Recovery_pct').n;
H.table('fo-summary',stages.map(k=>({condition:k,n:stat(k,'Recovery_pct').n,DBG:stat(k,'D_BG_px').mean,ADE:stat(k,'ADE_BG0_px').mean,FDE:stat(k,'FDE_BG0_px').mean,recovery:ci(stat(k,'Recovery_pct')),median:stat(k,'Recovery_pct').median,delta:ci(stat(k,'DeltaD_px')),GT_ADE:stat(k,'ADE_GT_px').mean,GT_FDE:stat(k,'FDE_GT_px').mean,correction:100*stat(k,'mean_active_FlowCorrection','pooled','condition_valid').mean})),[['condition','Flow window'],['n','n'],['DBG','D_BG px'],['ADE','BG0 ADE px'],['FDE','BG0 FDE px'],['recovery','Recovery % [95% CI]'],['median','Median %'],['delta','ΔD px [95% CI]'],['GT_ADE','GT ADE px'],['GT_FDE','GT FDE px'],['correction','Flow corrected %']]);
H.table('fo-paired',pr.filter(r=>['middle-early','middle-late','early-late'].includes(r.contrast)).map(r=>({...r,effect:ci(r)})),[['contrast','Paired contrast'],['n','n'],['effect','Mean %p [95% CI]'],['median','Median %p']]);
H.table('fo-tasks',D.tasks.map(t=>({task:t,n:stat('early','Recovery_pct',t).n,...Object.fromEntries(stages.map(k=>[k,stat(k,'Recovery_pct',t).mean]))})),[['task','Task'],['n','Paired n'],...stages.map(k=>[k,k+' recovery %'])]);
$('fo-noop').textContent=`Same-BGb no-op: BG8 ×6 tasks×3 seeds = ${D.noop.length} cases · 36-step raw flow, latent, decoded pixels exact match · trajectory Δ0 px (identical frames → deterministic baseline tracks reused).`;
H.table('fo-controls',pr.filter(r=>['early-background_early','full-background_full'].includes(r.contrast)).map(r=>({...r,effect:ci(r)})),[['contrast','Robot − far-background'],['n','Paired n'],['effect','Recovery advantage %p [95% CI]']]);
$('fo-interpretation').textContent=`BGb 관측을 고정한 Early robot-flow 교정의 작은 평균 회복은 flow 차이의 제한적인 인과 기여를 지지합니다. Middle 평균이 가장 크지만 task별 방향과 CI가 달라 보편적 핵심 단계는 확정할 수 없습니다. Full 뒤에도 표본별 평균 ${fmt(stat('full','Remaining_pct').mean,1)}%의 궤적 차이가 남습니다.`;
$('flow-only-validation').textContent=`Smoke 9조건 exact replay · 1620 cached flow-only cases verified · ${D.noop.length} BGb no-op cases exact · MuJoCo GT equality 96 checks. Observation-switch 결과는 본 분석에 사용하지 않습니다.`;
function render(){const t=$('task').value,s=+$('seed').value,b=$('bg').value,stage=$('fo-stage').value,choice=$('fo-group').value,group=choice==='task'?t:choice;
const r=D.correlations.find(r=>r.stage===stage&&r.x==='original_D_dir'&&r.y==='Recovery_pct'&&r.grouping===group);
$('fo-direction-result').textContent=`${stage} · n=${r.n} · Spearman ρ ${fmt(r.rho)} [95% CI ${fmt(r.rho_ci_low)}, ${fmt(r.rho_ci_high)}] · Pearson r ${fmt(r.pearson)} · per-task CI 미산출`;
let points=D.paired_metrics.filter(r=>r.condition===stage&&r.Recovery_pct!=null&&(choice!=='task'||r.task===t)).map(r=>({...r}));
if(choice==='task_demeaned')for(const task of D.tasks){const rs=points.filter(r=>r.task===task);for(const k of ['original_D_dir','Recovery_pct']){const m=rs.reduce((a,r)=>a+r[k],0)/rs.length;rs.forEach(r=>r[k]-=m);}}
H.chart('fo-direction',D.tasks.map(task=>({name:task,rows:points.filter(r=>r.task===task).map(r=>({x:r.original_D_dir,y:r.Recovery_pct,label:`seed${r.seed} ${r.background}`}))})),`Original mean 1 − cos(robot flow)${choice==='task_demeaned'?' (task-centered)':''}`,`Trajectory recovery (%)${choice==='task_demeaned'?' (task-centered)':''}`,true);
const vc=[['BG0',get(t,s,'BG0','baseline'),'BG0'],[b,get(t,s,b,'baseline'),'baseline'],...stages.map(k=>[k,get(t,s,b,k),k])];
const sig=vc.map(v=>v[1]?.video).join('|');if($('fo-videos').dataset.signature!==sig){$('fo-videos').dataset.signature=sig;$('fo-videos').innerHTML=vc.map(([label,c])=>`<div class="card"><b>${label}</b><div class="video"><video src="${c.video}" muted playsinline preload="metadata"></video><canvas width="256" height="256"></canvas></div></div>`).join('');videos=vc.map(v=>v[1]);}
H.trajectory('fo-tracks',vc.map(([l,c,k])=>[l,c,colors[k]]),old.truth[t]);
H.table('fo-metrics',D.metrics.filter(r=>r.task===t&&r.seed===s&&r.background===b&&['baseline',...stages].includes(r.condition)).map(r=>({...r,QC:r.paired_tracker_failed?'Excluded':'Valid'})),[['condition','조건'],['D_BG_px','D_BG px'],['ADE_BG0_px','BG0 ADE px'],['FDE_BG0_px','BG0 FDE px'],['Recovery_pct','Recovery %'],['DeltaD_px','ΔD px'],['ADE_GT_px','GT ADE px'],['FDE_GT_px','GT FDE px'],['confidence_min','Min conf.'],['QC','QC']]);
}
function draw(){document.querySelectorAll('#fo-videos video').forEach((v,i)=>{const c=videos[i],ctx=v.nextElementSibling.getContext('2d'),frame=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);if(!c)return;ctx.strokeStyle='#00ffff';ctx.lineWidth=1.5;ctx.beginPath();for(let j=0;j<=frame;j++){if(!c.valid[j])continue;if(j===0||!c.valid[j-1])ctx.moveTo(...c.track[j]);else ctx.lineTo(...c.track[j]);}ctx.stroke();if(c.valid[frame]){ctx.fillStyle='#00ffff';ctx.beginPath();ctx.arc(...c.track[frame],3,0,2*Math.PI);ctx.fill();}});requestAnimationFrame(draw);}
$('fo-play').onclick=()=>{const vs=[...document.querySelectorAll('#fo-videos video')],pause=vs.some(v=>!v.paused);vs.forEach(v=>{if(pause)v.pause();else{v.currentTime=vs[0].currentTime;v.play().catch(()=>{});}});};$('fo-reset').onclick=()=>document.querySelectorAll('#fo-videos video').forEach(v=>{v.pause();v.currentTime=0;});
['task','seed','bg','fo-stage','fo-group'].forEach(id=>$(id).addEventListener('change',render));render();draw();})();
