(()=>{'use strict';const F=window.LATE_SWITCH_DATA,D=window.INTERVENTION_DATA,H=window.INTERVENTION_RENDER_HELPERS,$=id=>document.getElementById(id),fmt=(v,n=2)=>v==null?'—':Number(v).toFixed(n);let videoCases=[];
const stat=(metric,group='pooled')=>F.summary.find(r=>r.group===group&&r.metric===metric),rec=stat('Recovery'),pref=stat('BG0_preference'),delta=stat('Delta_recovery_24_minus_12');
$('status').textContent+=` · Late 조건 전환 ${F.metrics.length}/270 · 새 추적 QC 제외 ${F.tracking_failures.length}건`;
$('ls-headline').textContent=`Late 전환 후 평균 회복 ${fmt(rec.mean*100)}% [95% CI ${fmt(rec.ci_low*100)}, ${fmt(rec.ci_high*100)}]% · 최종 궤적은 ${pref.ci_low>0?'BG0에 더 가까움':pref.ci_high<0?'BGb에 더 가까움':'어느 배경에 더 가까운지 불확실'} · Step12 전환 대비 회복 차이 ${fmt(delta.mean*100)}%p [${fmt(delta.ci_low*100)}, ${fmt(delta.ci_high*100)}]%p (paired n=${delta.n}).`;
H.table('ls-summary',[12,24].map(step=>{const r=stat('Recovery_step'+step),p=stat('BG0_preference_step'+step);return {condition:step===12?'BGb Early → BG0 Middle+Late':'BGb Early+Middle → BG0 Late',D_BG:F.pairs.reduce((a,b)=>a+b.D_BG_px_common,0)/F.pairs.length,D_int:F.pairs.reduce((a,b)=>a+b['D_step'+step+'_px_common'],0)/F.pairs.length,n:r.n,mean:r.mean*100,lo:r.ci_low*100,hi:r.ci_high*100,preference:p.mean};}),[['condition','관측 조건'],['n','Paired n'],['D_BG','D_BG px'],['D_int','To BG0 px'],['mean','회복 %'],['lo','95% CI low'],['hi','high'],['preference','상대적 근접성']]);
H.table('ls-task-summary',D.tasks.map(task=>({task,rec:stat('Recovery',task).mean*100,preference:stat('BG0_preference',task).mean,delta:stat('Delta_recovery_24_minus_12',task).mean*100,n:stat('Delta_recovery_24_minus_12',task).n})),[['task','Task'],['n','Paired n'],['rec','Late 전환 회복 %'],['preference','상대적 근접성'],['delta','Step24 − step12 회복 %p']]);
const robust=F.sensitivity.find(r=>r.minimum_baseline_px===1&&r.metric==='Recovery');$('ls-sensitivity').textContent=`원래 차이 D_BG≥1px인 ${robust.n}개 표본: Late 전환 회복 ${fmt(robust.mean*100)}% [95% CI ${fmt(robust.ci_low*100)}, ${fmt(robust.ci_high*100)}]%. 작은 baseline에서의 비율과 추적 오차에 주의합니다.`;
function render(){const t=$('task').value,s=+$('seed').value,b=$('bg').value,get=(bg,k)=>D.cases[`${t}|${s}|${bg}|${k}`];const cs=[['BG0 all',get('BG0','baseline'),'#172f40'],[`${b} all`,get(b,'baseline'),'#888'],[`${b} Early → BG0 Middle+Late`,get(b,'switch_bg_to_ref'),'#b57a42'],[`${b} Early+Middle → BG0 Late`,F.cases[`${t}|${s}|${b}|switch_bg_to_ref_late`],'#187b8b']];
H.table('ls-metrics',cs.map(([name,c])=>({...c.metric,condition:name,QC:c.metric.tracker_failed||c.metric.paired_tracker_failed?'Excluded':'Valid'})),[['condition','조건'],['D_BG_px','D_BG px'],['D_int_px','To BG0 px'],['D_to_BGb_px','To BGb px'],['Recovery','Recovery'],['ADE_GT','GT ADE px'],['FDE_GT','GT FDE px'],['confidence_min','Min conf.'],['valid_future_fraction','Valid fraction'],['QC','QC']]);
H.trajectory('ls-tracks',cs,D.truth[t]);H.chart('ls-latent',cs.slice(1).map(([name,c,color])=>({name,color,rows:c.latent.slice(0,36).map((r,i)=>({x:i/35,y:r[1]}))})),'Denoising progress (high → low noise)','Normalized robot latent distance to BG0');
const signature=cs.map(([name,c])=>c.video).join('|');if($('ls-videos').dataset.signature!==signature){$('ls-videos').dataset.signature=signature;$('ls-videos').innerHTML=cs.map(([name,c])=>`<div class="card"><b>${name}</b>${c.metric.tracker_failed?'<span class="small"> · QC excluded</span>':''}<div class="video"><video src="${c.video}" muted playsinline preload="metadata"></video><canvas width="256" height="256"></canvas></div></div>`).join('');videoCases=cs.map(([name,c])=>c);}}
function draw(){document.querySelectorAll('#ls-videos video').forEach((v,i)=>{const c=videoCases[i],ctx=v.nextElementSibling.getContext('2d'),last=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);if(!c)return;ctx.strokeStyle='#00ffff';ctx.lineWidth=1.5;ctx.beginPath();for(let j=0;j<=last;j++){if(!c.valid[j])continue;if(j===0||!c.valid[j-1])ctx.moveTo(...c.track[j]);else ctx.lineTo(...c.track[j]);}ctx.stroke();if(c.valid[last]){ctx.fillStyle='#00ffff';ctx.beginPath();ctx.arc(...c.track[last],3,0,Math.PI*2);ctx.fill();}});requestAnimationFrame(draw);}
$('ls-play').onclick=()=>{const vs=[...document.querySelectorAll('#ls-videos video')],playing=vs.some(v=>!v.paused),time=vs[0].currentTime;vs.forEach(v=>{if(playing)v.pause();else{v.currentTime=time;v.play().catch(()=>{});}});};$('ls-reset').onclick=()=>document.querySelectorAll('#ls-videos video').forEach(v=>{v.pause();v.currentTime=0;});
['task','seed','bg'].forEach(id=>$(id).addEventListener('change',render));render();draw();})();
