(()=>{'use strict';const F=window.MIDDLE_SWITCH_DATA,D=window.INTERVENTION_DATA,L=window.LATE_SWITCH_DATA,H=window.INTERVENTION_RENDER_HELPERS,$=id=>document.getElementById(id),fmt=(v,n=2)=>v==null?'—':Number(v).toFixed(n),st=(stage,metric,group='pooled')=>F.summary.find(r=>r.stage===stage&&r.metric===metric&&r.group===group);let videoCases=[];
const r=st('Middle-only','Recovery'),ab=st('Middle-only','absolute_improvement_px'),gt=st('Middle-only','GT_ADE_improvement_px');$('ms-headline').textContent=`Middle-only 평균 회복 ${fmt(r.mean*100)}% [95% CI ${fmt(r.ci_low*100)}, ${fmt(r.ci_high*100)}]% · n=${r.n} · ${r.ci_low>0?'회복률 증가 지지':r.ci_high<0?'회복률 악화':'회복률 증가 불확실'}. BG0 거리 감소 ${fmt(ab.mean,4)}px [${fmt(ab.ci_low,4)}, ${fmt(ab.ci_high,4)}]. GT ADE 개선 ${fmt(gt.mean,4)}px [${fmt(gt.ci_low,4)}, ${fmt(gt.ci_high,4)}].`;
$('status').textContent+=` · Middle-only 추가 ${Object.keys(F.cases).length}/270 · 새 추적 QC 제외 ${F.tracking_failures.filter(r=>r.stage==='Middle-only').length}건`;
H.table('ms-summary',['Early-only','Middle-only','Late-only'].map(stage=>{const r=st(stage,'Recovery');return {stage,n:String(r.n),D_BG:st(stage,'D_BG_px').mean,D_int:st(stage,'D_int_px').mean,rec:r.mean*100,med:r.median*100,lo:r.ci_low*100,hi:r.ci_high*100,ADE:st(stage,'ADE_GT').mean};}),[['stage','관측 전환 구간'],['n','n'],['D_BG','D_BG px'],['D_int','D_int px'],['rec','회복 %'],['med','중앙값 %'],['lo','95% CI low'],['hi','high'],['ADE','GT ADE px']]);
H.table('ms-paired',['E','L'].map(k=>{const r=st('paired','Delta_M_minus_'+k);return {name:k==='E'?'Middle − Early':'Middle − Late',n:String(r.n),mean:r.mean*100,lo:r.ci_low*100,hi:r.ci_high*100};}),[['name','Paired 비교'],['n','n'],['mean','회복 차이 %p'],['lo','95% CI low'],['hi','high']]);
H.table('ms-tasks',D.tasks.map(task=>({task,E:st('Early-only','Recovery',task).mean*100,M:st('Middle-only','Recovery',task).mean*100,L:st('Late-only','Recovery',task).mean*100,ME:st('paired','Delta_M_minus_E',task).mean*100,ML:st('paired','Delta_M_minus_L',task).mean*100,GT:st('Middle-only','GT_ADE_improvement_px',task).mean})),[['task','Task'],['E','Early %'],['M','Middle %'],['L','Late %'],['ME','paired M−E %p'],['ML','paired M−L %p'],['GT','Middle GT 개선 px']]);
const robust=F.sensitivity.find(r=>r.minimum_baseline_px===1&&r.stage==='Middle-only'&&r.metric==='Recovery');$('ms-sensitivity').textContent=`D_BG≥1px인 ${robust.n}개 표본: Middle-only 회복 ${fmt(robust.mean*100)}% [95% CI ${fmt(robust.ci_low*100)}, ${fmt(robust.ci_high*100)}]%.`;
function render(){const t=$('task').value,s=+$('seed').value,b=$('bg').value,key=(bg,k)=>`${t}|${s}|${bg}|${k}`,cs=[['BG0 reference',D.cases[key('BG0','baseline')],'#172f40'],[b+' baseline',D.cases[key(b,'baseline')],'#888'],['Early-only',D.cases[key(b,'switch_ref_to_bg')],'#bb784c'],['Middle-only',F.cases[key(b,'switch_middle_only')],'#167c89'],['Late-only',L.cases[key(b,'switch_bg_to_ref_late')],'#bd5070']];
const ms=F.metrics.filter(r=>r.task===t&&r.seed===s&&r.background===b);H.table('ms-metrics',cs.map(([name,c])=>{let r=ms.find(r=>r.stage===name)||c.metric;if(name==='BG0 reference'){const base=cs[1][1].metric;r={...r,D_BG_px:base.D_BG_px,D_int_px:0,D_to_BGb_px:base.D_BG_px,Recovery:base.Recovery==null?null:1,paired_tracker_failed:base.paired_tracker_failed};}return {...r,name,QC:r.tracker_failed||r.paired_tracker_failed?'Excluded':'Valid'};}),[['name','조건'],['D_BG_px','D_BG px'],['D_int_px','To BG0 px'],['D_to_BGb_px','To BGb px'],['Recovery','Recovery'],['ADE_GT','GT ADE px'],['FDE_GT','GT FDE px'],['confidence_min','Min conf.'],['valid_future_fraction','Valid fraction'],['QC','QC']]);
H.trajectory('ms-tracks',cs,D.truth[t]);H.chart('ms-latent',cs.slice(1).map(([name,c,color])=>({name,color,rows:c.latent.slice(0,36).map((r,i)=>({x:i/35,y:r[1]}))})),'Denoising progress (high → low noise)','Normalized robot latent distance to BG0');
const signature=cs.map(([name,c])=>c.video).join('|');if($('ms-videos').dataset.signature!==signature){$('ms-videos').dataset.signature=signature;$('ms-videos').innerHTML=cs.map(([name,c])=>`<div class="card"><b>${name}</b>${c.metric.tracker_failed?'<span class="small"> · QC excluded</span>':''}<div class="video"><video src="${c.video}" muted playsinline preload="metadata"></video><canvas width="256" height="256"></canvas></div></div>`).join('');videoCases=cs.map(([name,c])=>c);}}
function draw(){document.querySelectorAll('#ms-videos video').forEach((v,i)=>{const c=videoCases[i],ctx=v.nextElementSibling.getContext('2d'),last=Math.min(20,Math.floor(v.currentTime*10));ctx.clearRect(0,0,256,256);ctx.strokeStyle='#00ffff';ctx.lineWidth=1.5;ctx.beginPath();for(let j=0;j<=last;j++){if(!c.valid[j])continue;if(j===0||!c.valid[j-1])ctx.moveTo(...c.track[j]);else ctx.lineTo(...c.track[j]);}ctx.stroke();if(c.valid[last]){ctx.fillStyle='#00ffff';ctx.beginPath();ctx.arc(...c.track[last],3,0,Math.PI*2);ctx.fill();}});requestAnimationFrame(draw);}
$('ms-play').onclick=()=>{const vs=[...document.querySelectorAll('#ms-videos video')],playing=vs.some(v=>!v.paused),time=vs[0].currentTime;vs.forEach(v=>{if(playing)v.pause();else{v.currentTime=time;v.play().catch(()=>{});}});};$('ms-reset').onclick=()=>document.querySelectorAll('#ms-videos video').forEach(v=>{v.pause();v.currentTime=0;});
['task','seed','bg'].forEach(id=>$(id).addEventListener('change',render));render();draw();})();
